plot1<-png(file="plot3.png",width=480,height=480)

a<-read.table("household_power_consumption.txt",col.names = c("date","time","active_power","reactive_power","voltage","intensity","sub1","sub2","sub3"),sep=";")
d<-subset(a, date %in% c("1/2/2007","2/2/2007"))
sub1<-as.numeric(as.character(d$sub1))
sub2<-as.numeric(as.character(d$sub2))
sub3<-as.numeric(as.character(d$sub3))
par(mar=c(4.3,4,3.0,2))
t<-strptime(paste(d$date,d$time,sep=" "),"%d/%m/%Y %H:%M:%S")
plot(t,sub1,type="l",xlab="",ylab="Global Active Power (kilowatts)")
lines(t,sub2,col="red")
lines(t,sub3,col="blue")
legend("topright",lty=c(1,1,1),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"))
dev.off()
