plot1<-png(file="plot4.png",width=480,height=480)

a<-read.table("household_power_consumption.txt",col.names = c("date","time","active_power","reactive_power","voltage","intensity","sub1","sub2","sub3"),sep=";")
d<-subset(a, date %in% c("1/2/2007","2/2/2007"))
par(mfrow=c(2,2))#,mar=c(2,2,2,2)))
t<-strptime(paste(d$date,d$time,sep=" "),"%d/%m/%Y %H:%M:%S")
plot(t,as.numeric(as.character(d$active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(t,as.numeric(as.character(d$voltage)),type="l",ylab="Voltage",xlab="datetime")
sub1<-as.numeric(as.character(d$sub1))
sub2<-as.numeric(as.character(d$sub2))
sub3<-as.numeric(as.character(d$sub3))
plot(t,sub1,type="l",xlab="",ylab="Global Active Power (kilowatts)")
lines(t,sub2,col="red")
lines(t,sub3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),bty="n")
plot(t,as.numeric(as.character(d$reactive_power)),type="l",ylab="Global_reactive_power",xlab="datetime")
dev.off()
